# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Thu, 15 Nov 2018 13:24:16 +0000
*               @ALL          1
*               @user         8
