<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: lorena
 * Date: Thu, 15 Nov 2018 14:43:26 +0100
 */

$conf['title'] = 'CACIC';
$conf['lang'] = 'es';
$conf['template'] = 'flat';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
